# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env: COMPILER=clang++-5.0

before_install:
  - sudo apt-get update -qq
  - wget http://mirrors.kernel.org/ubuntu/pool/main/b/boost1.62/libboost1.62-dev_1.62.0+dfsg-4_amd64.deb
  - sudo dpkg -i libboost1.62-dev_1.62.0+dfsg-4_amd64.deb
script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - cmake --build . --target all
  - cmake --build . --target test
