matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - llvm-toolchain-trusty
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-6
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
    - eval "${MATRIX_EVAL}"
script:
    - mkdir build && cd build
    - cmake .. && cmake --build . --target all
